import { useEffect, useRef } from "react";
import Head from "next/head";
import Mysection from "../components/Mysection";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const section3 = useRef();
  const sectionAtlantic = useRef();
  const sectionPacific = useRef();
  const sectionArctic = useRef();
  const sectionSouth = useRef();
  const sectionIndian = useRef();
  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container ${styles.container}`}>
        <div ref={section1}>
          <Mysection
            image={`/images/Eugene_Isabey_Sea_Painting.jpg`}
            headline={`Explore the Five Oceans`}
            goToSectionRef={sectionAtlantic}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionAtlantic}>
          <Mysection
            image={`/images/Atlantic_Ocean.jpg`}
            headline={`Atlantic Ocean`}
            info={`There are many interesting things about the Atlantic Ocean`}
            goToSectionRef={sectionPacific}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionPacific}>
          <Mysection
            image={`/images/Pacific_Ocean.jpg`}
            headline={`Pacific Ocean`}
            info={`There are many interesting things about the Pacific Ocean`}
            goToSectionRef={sectionIndian}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionIndian}>
          <Mysection
            image={`/images/Indian_Ocean.jpg`}
            headline={`Indian Ocean`}
            info={`There are many interesting things about the Indian Ocean`}
            goToSectionRef={sectionSouth}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionSouth}>
          <Mysection
            image={`/images/Southern_Ocean.png`}
            headline={`Southern Ocean`}
            info={`There are many interesting things about the Southern Ocean`}
            goToSectionRef={sectionArctic}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionArctic}>
          <Mysection
            image={`/images/Arctic_Ocean.jpg`}
            headline={`Arctic Ocean`}
            info={`There are many interesting things about the Arctic Ocean`}
            goToSectionRef={section1}
            scrollTo={scrollTo}
            showArrow={false}
          />
        </div>
      </div>
    </div>
  );
}