import { useEffect, useRef } from "react";
import Head from "next/head";
import Mysection from "../components/Mysection";
import styles from "../styles/Home.module.scss";


export default function Home() {
  const section1 = useRef();
  const section2 = useRef();
  const sectionAtlantic = useRef();
  const sectionPacific = useRef();
  const sectionArctic = useRef();
  const sectionSouth = useRef();
  const sectionIndian = useRef();
  function scrollTo(section) {
    section.current.scrollIntoView({ behavior: "smooth" });
  }
  return (
    <div>
      <Head>
        <title>Learn About the Oceans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`container ${styles.container}`}>
        <div ref={section1}>
          <Mysection
            image={`/images/Eugene_Isabey_Sea_Painting.jpg`}
            headline={`Explore the Five Oceans`}
            goToSectionRef={sectionAtlantic}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionAtlantic}>
          <Mysection
            image={`/images/Atlantic_Ocean.jpg`}
            headline={`Atlantic Ocean`}
            info={`The second largest Ocean, it’s home to over 200,000 marine species. 
            It covers 85,133,000 km2 (32,870,000 sq mi) otherwise known as ⅕ of the earth’s surface. 
            It’s connected to all the other oceans. 
            The deepest part is the Puerto Rico trench which is 8,376 m (27,480 ft) deep. 
            It’s the resting place of the Titanic and her passengers as well as the people from the Titan submersible. 
            It’s also home to the Bermuda Triangle.`}
            goToSectionRef={sectionPacific}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionPacific}>
          <Mysection
            image={`/images/Pacific_Ocean.jpg`}
            headline={`Pacific Ocean`}
            info={`The largest ocean, it covers more than 30% of the earth’s surface and contains over 200,000 marine species. 
            It has over 25,000 islands. It’s home to the great barrier reef. 
            The deepest part is the Challenger Deep which is also the deepest point in the world. 
            It’s about 38,000 ft deep. It’s the most polluted ocean containing around 2 trillion plastic pieces.`}
            goToSectionRef={sectionIndian}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionIndian}>
          <Mysection
            image={`/images/Indian_Ocean.jpg`}
            headline={`Indian Ocean`}
            info={`The 3rd largest ocean in the world. It covers around 70,560,000 km2 (27,240,000 sq mi). 
            It contains over 15,000 marine species. 
            Its deepest point is the Java Trench which is around 24,000 ft deep. 
            It’s the warmest ocean in the world and because of that it has limited ocean life.
            It’s being hurt by pollution and overfishing. It has about 40% of the world’s oil deposits. `}
            goToSectionRef={sectionSouth}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionSouth}>
          <Mysection
            image={`/images/Southern_Ocean.jpg`}
            headline={`Southern Ocean`}
            info={`The 4th largest ocean in the world it covers around 20,327,000 km2 (7,848,000 sq mi). 
            It’s home to around 9,000 species. Its deepest point is around 24,000ft. 
            It contains the Drake Passage which is a passageway that you need to travel through to get to Antarctica. 
            It’s home to the blue whale which is the largest animal on earth. There are massive icebergs in the ocean.`}
            goToSectionRef={sectionArctic}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={sectionArctic}>
          <Mysection
            image={`/images/Arctic_Ocean.jpg`}
            headline={`Arctic Ocean`}
            info={`The smallest and shallowest ocean it contains around 5,000 marine species. 
            It covers 14,060,000 km2 (5,430,000 sq mi) of the world. The deepest part is only around 18,000ft. 
            It has an abundance of natural resources such as fresh water reserves and fossil fuels. 
            It also contains a lot of fisheries. 
            A large amount of the ocean is covered in ice which has been gradually melting due to global warming.`}
            goToSectionRef={section2}
            scrollTo={scrollTo}
            showArrow={true}
          />
        </div>
        <div ref={section2}>
          <Mysection
            image={`/images/Monet_Water_Lilies.webp`}
            headline={`Additional Resources`}
            goToSectionRef={section1}
            scrollTo={scrollTo}
            showArrow={false}
          />
        </div>
        Want to know a secret?
        <br/>
        Why don't you keep scrolling?
        <br/>
        Farther...
        <br/>
        <br/>
        <br/>
        Farther...
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        Almost there...
        <br/>
        <br/>
        <br/>
        <br/>
        <a href='https://www.youtube.com/watch?v=dQw4w9WgXcQ&themeRefresh=1'>Click here</a>
      </div>
    </div>
  );
}